export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
export const SHOW_CART_DLG = "SHOW_CART_DLG";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const SET_CHECKEDOUT_ITEMS = "SET_CHECKEDOUT_ITEMS";
export const REMOVE_CHECKEDOUT_ITEMS = "REMOVE_CHECKEDOUT_ITEMS";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const LOGOUT = "LOGOUT";
export const SET_CREATE_CATEGORY_ERROR = "SET_CREATE_CATEGORY_ERROR";
export const REMOVE_CREATE_CATEGORY_ERROR = "REMOVE_CREATE_CATEGORY_ERROR";

//show the Alert Dialog
export const SHOW_ALERT_DIALOG = "SHOW_ALERT_DIALOG";

//categories
export const CATEGORIES_FETCHED = "CATEGORIES_FETCHED";

//Place orders
export const PLACE_ORDER = "PLACE_ORDER";